# Generated by Django 3.2.5 on 2021-10-10 11:23

from django.db import migrations, models
import djongo.models.fields
import timer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('timer_name', models.CharField(max_length=255)),
                ('exercise_list', djongo.models.fields.EmbeddedField(model_container=timer.models.Exercise)),
                ('exercise_time', models.IntegerField()),
                ('rest_time', models.IntegerField()),
                ('time_between_cycle', models.IntegerField()),
                ('ready_time', models.IntegerField()),
                ('cycle_count', models.IntegerField()),
                ('round_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'timer',
            },
        ),
    ]
