# Generated by Django 3.2.5 on 2021-10-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
